# Generated by Django 5.0.5 on 2024-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('item_url', models.URLField()),
                ('cover_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(max_length=255)),
                ('instruments', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('lead_time', models.CharField(max_length=255)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
