# Generated by Django 5.0.5 on 2024-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('item_url', models.URLField()),
                ('cover_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('instruments', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('lead_time', models.CharField(max_length=255)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publisher', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
