# Generated by Django 5.0.5 on 2024-05-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sheetmusic_artist_alter_sheetmusic_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
