# Generated by Django 5.0.6 on 2024-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sheetmusic_title_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('published', models.DateField(auto_now=True)),
                ('author', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
