# Generated by Django 5.0.6 on 2024-08-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.sheetmusic'),
        ),
    ]
