# Generated by Django 5.0.6 on 2024-08-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsitem_related_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
